// Mock data for ChakriKhujo platform

export const mockJobs = [
  {
    id: "job_1",
    title: "Senior Full Stack Developer",
    company: "TechCorp Inc.",
    companyLogo: "https://ui-avatars.com/api/?name=TechCorp&background=0ea5e9&color=fff",
    location: "San Francisco, CA",
    type: "Full-time",
    remote: true,
    salary: "$120,000 - $160,000",
    description: "We're looking for a senior full stack developer to join our growing team...",
    requirements: [
      "5+ years of experience with React and Node.js",
      "Experience with TypeScript",
      "Strong understanding of database design",
      "Experience with cloud platforms (AWS/GCP)",
    ],
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    posted: "2024-01-15",
    deadline: "2024-02-15",
    applicants: 45,
    avgAtsScore: 76,
    status: "active",
    matchScore: 92,
    tags: ["Best Fit", "Remote"],
  },
  {
    id: "job_2",
    title: "Product Manager",
    company: "StartupXYZ",
    companyLogo: "https://ui-avatars.com/api/?name=StartupXYZ&background=16a34a&color=fff",
    location: "New York, NY",
    type: "Full-time",
    remote: false,
    salary: "$110,000 - $140,000",
    description: "Join our product team to shape the future of our platform...",
    requirements: [
      "3+ years of product management experience",
      "Experience with agile methodologies",
      "Strong analytical skills",
      "MBA preferred",
    ],
    skills: ["Product Strategy", "Agile", "Analytics", "Roadmapping"],
    posted: "2024-01-20",
    deadline: "2024-02-20",
    applicants: 32,
    avgAtsScore: 68,
    status: "active",
    matchScore: 78,
    tags: ["Quick Apply"],
  },
  {
    id: "job_3",
    title: "UI/UX Designer",
    company: "DesignStudio",
    companyLogo: "https://ui-avatars.com/api/?name=DesignStudio&background=dc2626&color=fff",
    location: "Austin, TX",
    type: "Contract",
    remote: true,
    salary: "$80 - $120/hour",
    description: "Create beautiful and intuitive user experiences...",
    requirements: [
      "4+ years of UI/UX design experience",
      "Proficiency in Figma and Adobe Creative Suite",
      "Portfolio demonstrating user-centered design",
      "Experience with design systems",
    ],
    skills: ["Figma", "User Research", "Prototyping", "Design Systems"],
    posted: "2024-01-18",
    deadline: "2024-02-18",
    applicants: 28,
    avgAtsScore: 82,
    status: "active",
    matchScore: 85,
    tags: ["Remote", "Contract"],
  },
];

export const mockCandidates = [
  {
    id: "candidate_1",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@email.com",
    avatar: "https://ui-avatars.com/api/?name=Emily+Rodriguez&background=8b5cf6&color=fff",
    title: "Senior Frontend Developer",
    location: "Seattle, WA",
    experience: "6 years",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "GraphQL"],
    atsScore: 94,
    resumeUrl: "/resumes/emily-rodriguez.pdf",
    appliedJobs: ["job_1"],
    status: "interviewing",
    lastActivity: "2024-01-22",
    notes: "Strong technical background, excellent communication skills",
    education: "BS Computer Science - University of Washington",
    currentRole: "Senior Frontend Developer at Microsoft",
  },
  {
    id: "candidate_2",
    name: "Michael Chen",
    email: "michael.chen@email.com",
    avatar: "https://ui-avatars.com/api/?name=Michael+Chen&background=f59e0b&color=fff",
    title: "Full Stack Developer",
    location: "Austin, TX",
    experience: "4 years",
    skills: ["React", "Node.js", "Python", "Docker", "AWS"],
    atsScore: 87,
    resumeUrl: "/resumes/michael-chen.pdf",
    appliedJobs: ["job_1", "job_2"],
    status: "applied",
    lastActivity: "2024-01-21",
    notes: "Good problem-solving skills, quick learner",
    education: "MS Computer Science - UT Austin",
    currentRole: "Software Engineer at Dell",
  },
  {
    id: "candidate_3",
    name: "Sarah Kim",
    email: "sarah.kim@email.com",
    avatar: "https://ui-avatars.com/api/?name=Sarah+Kim&background=ef4444&color=fff",
    title: "Product Designer",
    location: "San Francisco, CA",
    experience: "5 years",
    skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Accessibility"],
    atsScore: 91,
    resumeUrl: "/resumes/sarah-kim.pdf",
    appliedJobs: ["job_3"],
    status: "offered",
    lastActivity: "2024-01-23",
    notes: "Exceptional design portfolio, strong user-centered approach",
    education: "BFA Design - Art Center College of Design",
    currentRole: "Senior UX Designer at Airbnb",
  },
];

export const mockInterviews = [
  {
    id: "interview_1",
    candidateId: "candidate_1",
    jobId: "job_1",
    date: "2024-01-25",
    time: "10:00 AM",
    duration: 60,
    type: "Technical",
    interviewers: ["Sarah Chen", "John Doe"],
    status: "scheduled",
    meetingLink: "https://zoom.us/j/123456789",
    questions: [
      "Tell me about your experience with React hooks",
      "How do you handle state management in large applications?",
      "Describe a challenging technical problem you solved recently",
    ],
    notes: "",
  },
  {
    id: "interview_2",
    candidateId: "candidate_2",
    jobId: "job_1",
    date: "2024-01-26",
    time: "2:00 PM",
    duration: 45,
    type: "Cultural Fit",
    interviewers: ["Sarah Chen"],
    status: "completed",
    meetingLink: "https://zoom.us/j/987654321",
    questions: [
      "What motivates you in your work?",
      "How do you handle conflict in a team?",
      "Where do you see yourself in 5 years?",
    ],
    notes: "Great cultural fit, enthusiastic about the role",
    rating: 4,
  },
];

export const mockApplications = [
  {
    id: "app_1",
    jobId: "job_1",
    job: mockJobs[0],
    status: "applied",
    appliedDate: "2024-01-20",
    lastUpdate: "2024-01-22",
    notes: "Application submitted successfully",
  },
  {
    id: "app_2",
    jobId: "job_2",
    job: mockJobs[1],
    status: "interview",
    appliedDate: "2024-01-18",
    lastUpdate: "2024-01-24",
    notes: "Phone screening completed, technical interview scheduled",
    interviewDate: "2024-01-26",
  },
  {
    id: "app_3",
    jobId: "job_3",
    job: mockJobs[2],
    status: "offer",
    appliedDate: "2024-01-15",
    lastUpdate: "2024-01-25",
    notes: "Offer received, reviewing terms",
    offerAmount: "$95/hour",
  },
];

export const mockSkills = [
  { name: "JavaScript", level: 90, demand: "High", growth: "+15%" },
  { name: "React", level: 85, demand: "High", growth: "+20%" },
  { name: "TypeScript", level: 75, demand: "High", growth: "+25%" },
  { name: "Node.js", level: 80, demand: "High", growth: "+18%" },
  { name: "Python", level: 70, demand: "High", growth: "+22%" },
  { name: "AWS", level: 65, demand: "High", growth: "+30%" },
  { name: "Docker", level: 60, demand: "Medium", growth: "+12%" },
  { name: "GraphQL", level: 55, demand: "Medium", growth: "+35%" },
];

export const mockCareerPaths = [
  {
    id: "path_1",
    current: "Frontend Developer",
    target: "Full Stack Developer",
    timeframe: "6-12 months",
    skillGaps: ["Node.js", "Database Design", "API Development"],
    resources: [
      {
        title: "Complete Node.js Developer Course",
        type: "course",
        provider: "Udemy",
        duration: "40 hours",
        rating: 4.6,
      },
      {
        title: "PostgreSQL Fundamentals",
        type: "tutorial",
        provider: "FreeCodeCamp",
        duration: "8 hours",
        rating: 4.8,
      },
    ],
    salary: {
      current: "$85,000",
      target: "$110,000",
      increase: "+29%",
    },
  },
  {
    id: "path_2",
    current: "Frontend Developer",
    target: "Tech Lead",
    timeframe: "2-3 years",
    skillGaps: ["Leadership", "System Design", "Mentoring"],
    resources: [
      {
        title: "Engineering Leadership Handbook",
        type: "book",
        provider: "Amazon",
        duration: "12 hours read",
        rating: 4.7,
      },
      {
        title: "System Design Interview Course",
        type: "course",
        provider: "Educative",
        duration: "25 hours",
        rating: 4.5,
      },
    ],
    salary: {
      current: "$85,000",
      target: "$140,000",
      increase: "+65%",
    },
  },
];

export const mockInterviewSessions = [
  {
    id: "session_1",
    type: "behavioral",
    date: "2024-01-20",
    questionsAnswered: 8,
    duration: "25 minutes",
    confidence: 85,
    strengths: ["Clear storytelling", "Good examples", "Confident delivery"],
    improvements: ["More specific metrics", "Connect to role requirements"],
  },
  {
    id: "session_2", 
    type: "technical",
    date: "2024-01-18",
    questionsAnswered: 6,
    duration: "20 minutes", 
    confidence: 78,
    strengths: ["Strong technical knowledge", "Problem-solving approach"],
    improvements: ["Explain thinking process", "Consider edge cases"],
  },
  {
    id: "session_3",
    type: "general",
    date: "2024-01-15",
    questionsAnswered: 5,
    duration: "15 minutes",
    confidence: 82,
    strengths: ["Good company research", "Clear motivation"],
    improvements: ["Ask more questions", "Show enthusiasm"],
  },
];

export const mockAnalytics = {
  recruiter: {
    totalJobs: 15,
    totalApplicants: 342,
    avgAtsScore: 74,
    interviewsScheduled: 28,
    offersExtended: 8,
    hiresCompleted: 5,
    timeToHire: 23, // days
    hiringFunnel: [
      { stage: "Applied", count: 342 },
      { stage: "Screened", count: 156 },
      { stage: "Interviewed", count: 67 },
      { stage: "Offered", count: 23 },
      { stage: "Hired", count: 15 },
    ],
    biasAudit: {
      gender: { male: 52, female: 48 },
      age: { "20-30": 35, "30-40": 40, "40-50": 20, "50+": 5 },
      education: { bachelor: 60, master: 35, phd: 5 },
    },
  },
  seeker: {
    profileViews: 156,
    jobApplications: 23,
    interviewRequests: 8,
    offers: 2,
    responseRate: 35, // percentage
    avgResponseTime: 3.2, // days
    interviewPractice: {
      sessionsCompleted: 3,
      avgConfidence: 82,
      totalQuestions: 19,
      improvementRate: 15, // percentage
    },
  },
};